version: '3'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692

  # redis:
  #   image: redis
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   volumes: 
  #     - redis:/data

  # seq:
  #   image: datalust/seq 
  #   container_name: seq
  #   restart: unless-stopped
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - 5341:80

volumes:
  postgres:
    driver: local
  # redis:
  #   driver: local